language: node_js
sudo: required
dist: trusty
before_script:
- npm install -g bower polylint web-component-tester
- bower install
- polylint -i *.html demo/*
env:
  global:
  - secure: gZ5vpMlc9fuKSZeMmT6xf4+FIVWxET6f6Lkp6l5Qo9vL2X/KC/bMJF1v2w5xXFLFTdm/hPUDkeQRDUBBJhGcsXhJeWIvAXdPkObV9ZPRwpDnnN1qU5lOqVIy6gFjDm2Wm6UNXcRnyP1TrGpMwbG13EUtD0rF8LZqBm3B833sKS4=
  - secure: DObDewETPYiIsASeC3UETPbQ6YBniRZdNV2eTM1xULvuFNDxXJD09KKyWOiMduublEIJRXLjBIXmD8cbVsgrbRUYA4bxcXffDeuc6q6HaQGU9HvIbLz6o3/oxi4fX2G9GwrZtijW2p2Rgw2l9koR3ovjcM97CSTWFUMh5rtXag8=
  - secure: gYk+x98hjMlSXZuMdp+7FeO5wkvIuN5pQcRBuDoTQ79CXWBQyhUImkBwx0znovZkOnOJJ58DCAsQ0/pNeeAyD98wYSZQRTcTJvQKUq3Sxq7ZAFEOc/M5r7IE4gSRw3R7gRvyZUuXijiubMGdaJQ4NN30s3ZlzIlXo46q8jttF+aH1kAblpQlilGy6u9zD/ESs4WUSvH9PiChUKoYFiYTIKHCcD/A9qFQ5cPWVoEID6ADfK/+gdKCPMdk414uOp64SbZfQeB8wKR2eQ8PzsOi7n33I9n4+dLgNtlrC2AVUIY+0Gud84RhKUoniWAqCq9GSBnzxx/Sy0bkr2gXExWgReCEoyIPRssjlGat1FDhXIEF0yumFsv4wOdx/h+mIbaxP9hpft5wS1RmYz63oOq7ZP1grWsPJDBZsoswe6JxUxNsFX5UGMNAzOVoLoCpIbpPDCXn1FaQE2TOm2ZAIiT5cr7PegO39Ib+cC6UFB/oXU3X1r6kV/fPwc6Y3pG+gq+I1LhYndekF0ZFkrDKc37C9JqfngzPJaNfoAWvQRY/BOqnb7DN+CPURXeMHFfr/S6DP+K2Wo9oWVK2lN3v7OSr9+Q4TW0tY9Ca1PyB4JdOZ89hQlyNsWN7GZsDOr7+5zi8o4rCtL0hr7SRTyBa6w2AruxyR61785/r6cI0q+THNfg=
  - secure: bAE/2l5OP0ehZ3Aj/lpNyilcYXL8wYGjVLa9bGqzP3x0zf2BqsUOPIawmYQ1jUVfa1BDsgYdjbMJkHO2gbApNv2/UDZhaRbDvoPTv2RlBYSChUb61kh7O/o/+7BVEAsDXDRwjgzLS7cZ5aOROZI1f/RIdNOUkpSPhcfVRAULHGdBsRVIp8oLHGdcdKDjkt7dUHP9KcQtsO8MqhQq2/3RfW8rMVxAfqqiAWL1ptNMn3iIZCG+BF+w4yhwokEZ6CllemMqhj/kh1oxH0D1YOZEmq1jHgimohF2Cg2EvU6RAl0NZDlNjLKfiR6tQCYvGQ3w2mIq0UJm+j4YjS0C0WOa+UzDXkoriPW7PBtPRqt6MsKm49xdmO5HSR9xUpfG1Me5/keeWwEOL9u9bte4MwN4vE58EVzetUraISdNgdlWSG19b5Enfs0eeglCSBPzm3tA5J0FwFo/U7YhVimlHoxZ9ydM1OEnXbfZam60quaMbpc8wB7YmvgtTzGVu0Y0JEeYKWlOmAEIfHW8mndXJgKhIGaUEE7usbsim+hjjNF+BHYXCobfWJYzI+oMlWt1O+xfftZavOo2TOX/iUhRcq775hvJ7869wfDO7fNshTX1ZwLP47CPGkiWPQJUNpcwFolku2yIhY14/pxKVUD4JjmO+MtKu6cD1ATjMTiBRze5ilM=
node_js: stable
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
script:
- xvfb-run wct
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct -s 'default'; fi
