language: node_js
node_js: stable
dist: trusty
sudo: required
addons:
  firefox: '46.0'
  sauce_connect: true
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install -g bower polylint web-component-tester
- bower install
- polylint
script:
- xvfb-run wct
env:
  global:
  - secure: UsZWS4nJ5QzFxiQShE2EOo4eS66g1BM9cwdNfz764jfGmCDJTUFMjWp5YRQrFl9Ml1/h3efI1ymXm91Od2NzktZ4J5bvskgquOGPdAEFf9T5PGW18AgLMlysaaBA/Jnr1UdinxDTx9P8/48F5f3LKnEkaAJ29MwlLmSpnlAeazVzbF5i7rNuzdK4DSxEBSadRY3BnPE8Y5BokYw4x3eqZj42zqKJcZ6jg6ArExvUE/FTii8IZZfpaoFn3Q7VIVXO6JDgyeExPU3brpkL9ha1y/PnBdov/6vae2K2XUbEJmv3QPZMhhMI0fh4dYhe63uMsFLnHQD1DGG6TVhuc+Jh/pneo4YhSqJ/B2T6owXq7lyqwK7G2xg3sDiWR7qB6hlkQhr2CQbD9ilGHNWqvdcNzbHrbtjvtdbBsRjFKyZKB1TiThCsCQHQvuWR8RRnhGhGlF77DwoT3e1taA5B2BFuM6u6sMQ6nZckRQ9dLEnTtEoWFYM8+bY9s0JcgKC9JKRgDqBIoaTiOIDKoCfVPMhwaFB+7/1ZlMZXk2VCwtl/bBwcLJAA8DcBT7FUjfFqAlyU3yNPVlxDrJ4xL87K28YHgpQRar3aXxsBVKxjIYV4GCT4Ef6V/YAPh7uyT0Pl4qbpfD0cQVbpLdVWn1kYIDCNxg6qGS4JXtAe1lGGQQtjdJQ=
  - secure: r/6lW1X5Jl+FII8mVBojO1+KQ5u95aeVZMVEATVfkIa/JNELLADDE9JuJdh56pRkgNw4b6imoEGhyvQa7fXPcs6ChpiQvxhkp4fosbQwpvr4QaUHwVRgkPMTb/MTFJo52LdeHQwRQFyMa852BknrSqkIWGNi49btn7Li1lKDaejNuhw/xjL8NLZykGsE/mBgGN1AGmExzqO69BaK72JqgJx6y9FtjzvBQ+P2Ci/CzukAVT2wswp0wZ7TY+VHZ3ceRavKn92yNNlgn6kMk/q29xgCUvswT7JgG/Z14za839jbOFkS9E6OZYyswFk/6iVauaQ1XYv6zyp64c9643ObDkzWgfyUtpKp1CcT/fYmW/vqt8RRapo+b7RMjECLaRnG82R1RqnndRb6Wmv56gIxsKfJ0/CjPM2Ax5tqZSnJ1RJw2Di8HybwMMgyKDkM+4ZMYg3Q1eqlcAoGrJ1arDhB58+zM9qAhh29a992K/srJ5zfc1naEBGzv5mTUTGasOvE7mFRe4CgXC6ilBEi8w1JcgAw39yaedG3obmPNQQ5QAIElArAEoSPiq5SuFA9aIOdOl26Mu2iaR+dN5/frbRpt9G+jNHZY7T9iz6I74GYOOi9BMpDEyys+7jgz9ayjDkiKE2WgoR4jRc6oUY5y7d/mcgk7vn4H8EeZNw+BN543tU=
